/**
 * Deep links — open the viewer with a document already loaded.
 *
 *   #data=<payload>      preferred: a fragment never reaches the server
 *   ?data=<payload>      same, but the document lands in CDN and access logs
 *   ?data=clipboard      read the document from the user's clipboard instead
 *   &view=text|tree|graph  which tab to open on (default: tree)
 *
 * `payload` is either raw JSON or base64url-encoded raw-deflate, told apart by
 * its first character — base64url can never start with `{`, `[` or `"`. That
 * keeps the contract copy-pasteable by hand while staying compact for links
 * generated by code. See docs/DEEP_LINKS.md for the producer side.
 */

export type DeepLinkView = "text" | "viewer" | "graph";

export interface DeepLink {
  payload: string;
  view?: DeepLinkView;
}

/**
 * Ceiling on a decoded document. A few KB of deflate can expand to hundreds of
 * MB, so this is enforced while the stream is read, not after it has landed.
 */
const MAX_DECODED_BYTES = 10 * 1024 * 1024;

/**
 * Longest payload we will hand out. Browsers accept far more, but CDN and proxy
 * request-line limits start rejecting somewhere above 8KB; documents past this
 * travel by clipboard instead.
 */
export const MAX_PAYLOAD_LENGTH = 4000;

export const CLIPBOARD_PAYLOAD = "clipboard";

export const canCompress = typeof CompressionStream !== "undefined";

// Accept the name each caller would reach for first rather than making them
// learn ours.
const VIEW_ALIASES: Record<string, DeepLinkView> = {
  text: "text",
  json: "text",
  raw: "text",
  tree: "viewer",
  viewer: "viewer",
  graph: "graph",
  visualizer: "graph",
};

/** Pull a deep link out of `location`, fragment first. */
export function readDeepLink(search: string, hash: string): DeepLink | null {
  const fragment = new URLSearchParams(hash.replace(/^#/, ""));
  const query = new URLSearchParams(search);
  // URLSearchParams has already percent-decoded these; decoding again would
  // corrupt any literal `%` inside a raw-JSON payload.
  const payload = fragment.get("data") ?? query.get("data");
  if (!payload) return null;

  const view = fragment.get("view") ?? query.get("view");
  return {
    payload,
    view: view ? VIEW_ALIASES[view.trim().toLowerCase()] : undefined,
  };
}

function base64UrlToBytes(value: string): Uint8Array {
  const base64 = value.replace(/-/g, "+").replace(/_/g, "/");
  const binary = atob(base64.padEnd(Math.ceil(base64.length / 4) * 4, "="));
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

function bytesToBase64Url(bytes: Uint8Array): string {
  let binary = "";
  // Chunked so a large document doesn't blow the argument limit of `apply`.
  const CHUNK = 0x8000;
  for (let i = 0; i < bytes.length; i += CHUNK) {
    binary += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
  }
  return btoa(binary)
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

async function inflate(payload: string): Promise<string> {
  const stream = new Blob([base64UrlToBytes(payload)])
    .stream()
    .pipeThrough(new DecompressionStream("deflate-raw"));

  const reader = stream.getReader();
  const decoder = new TextDecoder();
  let text = "";
  let decoded = 0;

  // Read incrementally so a compression bomb is abandoned mid-stream rather
  // than inflated into memory and measured afterwards.
  for (;;) {
    const {done, value} = await reader.read();
    if (done) break;
    decoded += value.byteLength;
    if (decoded > MAX_DECODED_BYTES) {
      await reader.cancel();
      throw new Error("The linked document is too large to open.");
    }
    text += decoder.decode(value, {stream: true});
  }

  return text + decoder.decode();
}

/** Turn a `data=` payload back into JSON text. */
export async function decodePayload(payload: string): Promise<string> {
  const trimmed = payload.trim();
  if (/^[[{"]/.test(trimmed)) return trimmed;

  if (!canCompress) {
    throw new Error("This browser cannot open compressed links.");
  }

  try {
    return await inflate(trimmed);
  } catch (error) {
    // A bomb reports its own (accurate) size message; everything else is a
    // mangled link, which is what a truncated copy-paste looks like.
    if (error instanceof Error && error.message.includes("too large"))
      throw error;
    throw new Error("This link is damaged or incomplete.");
  }
}

/** Compress JSON text into a `data=` payload. */
export async function encodePayload(json: string): Promise<string> {
  const stream = new Blob([json])
    .stream()
    .pipeThrough(new CompressionStream("deflate-raw"));
  const buffer = await new Response(stream).arrayBuffer();
  return bytesToBase64Url(new Uint8Array(buffer));
}

/**
 * Build a shareable link, or `null` when the document is too big to travel in a
 * URL — those go by clipboard, which only the producer can fill.
 *
 * `view` carries the tab the link should open on, so a link made from the
 * Visualizer arrives in the Visualizer. It is omitted for "viewer", which is
 * what a link with no view already opens on — a flag that only ever restates
 * the default is length the recipient has to copy for nothing.
 */
export async function buildShareLink(
  json: string,
  view?: DeepLinkView,
  base = `${window.location.origin}${window.location.pathname}`
): Promise<string | null> {
  if (!canCompress) return null;
  const payload = await encodePayload(json);
  if (payload.length > MAX_PAYLOAD_LENGTH) return null;
  const tab = view && view !== "viewer" ? `&view=${view}` : "";
  return `${base}#data=${payload}${tab}`;
}
